In [ ]:
# https://habr.com/ru/company/skillfactory/blog/564240/

In [2]:
import numpy as np

In [45]:
# Создание одномерного массива

# С указанием значения
a = np.array([1, 2, 3])
print(a)

# С указанием длины и заполненного нулями
aZero = np.zeros(3)
print(aZero)

# С указанием длины и заполненного единицами
aOne = np.ones(3)
print(aOne)

# С указанием длины и заданным значением
aOne = np.full(3, 3)
print(aOne)

# С указанием длины и заполненного случайными значениями
aRandom = np.random.random(3)
print(aRandom)

[1 2 3]
[0. 0. 0.]
[1. 1. 1.]
[3 3 3]
[0.06713618 0.33876512 0.52059965]


In [4]:
# Арифметические операции с одномерным массивом
a1 = np.array([1, 2, 4, 8, 16])
a2 = np.ones(np.size(a1))

# Сложение двух массивов
aAddition = a1 + a2
print("Сумма массивов ", a1, " и ", a2, " = ", aAddition)

# Вычитание двух массивов
aSubtraction = a1 - a2
print("Разница массивов ", a1, " и ", a2, " = ", aSubtraction)

# Произведение двух массивов
aMultiplication = aAddition * aSubtraction
print("Произведение массивов ", aAddition, " и ", aSubtraction, " = ", aMultiplication)

# Деление двух массивов
aDivision =  aMultiplication / a1
print("Отношение массивов ", aMultiplication, " и ", a1, " = ", aDivision)

# Добавление к массиву числа
aAddNum = a1 + 2
print("Сумма ", a1, " и 2 = ", aAddNum)

# Вычитание из массива числа
aSubtractNum = aAddNum - 1
print("Разница ", aAddNum, " и 1 = ", aSubtractNum)

# Умножение массива на число
aMultiplyNum = a1 * 2
print("Произведение ", a1, " и 2 = ", aMultiplyNum)

# Деление массива на число
aDivisionNum = a1 / 2
print("Отношение ", a1, " и 2 = ", aDivisionNum)

Сумма массивов  [ 1  2  4  8 16]  и  [1. 1. 1. 1. 1.]  =  [ 2.  3.  5.  9. 17.]
Разница массивов  [ 1  2  4  8 16]  и  [1. 1. 1. 1. 1.]  =  [ 0.  1.  3.  7. 15.]
Произведение массивов  [ 2.  3.  5.  9. 17.]  и  [ 0.  1.  3.  7. 15.]  =  [  0.   3.  15.  63. 255.]
Отношение массивов  [  0.   3.  15.  63. 255.]  и  [ 1  2  4  8 16]  =  [ 0.      1.5     3.75    7.875  15.9375]
Сумма  [ 1  2  4  8 16]  и 2 =  [ 3  4  6 10 18]
Разница  [ 3  4  6 10 18]  и 1 =  [ 2  3  5  9 17]
Произведение  [ 1  2  4  8 16]  и 2 =  [ 2  4  8 16 32]
Отношение  [ 1  2  4  8 16]  и 2 =  [0.5 1.  2.  4.  8. ]


In [44]:
# Индексирование в одномерном массиве
a = np.random.randint(low=0, high=10, size=10)
print(a)

# Получить 3 элемент
print(a[2])

# Получить первые 2 элемента
print(a[:2])

# Получить все элементы, начиная с 3
print(a[2:])

# Получить элементы с 3 по 4
print(a[2:4])

# Получить все элементы с 1 по 9 с шагом 3
print(a[1:9:3])

[2 9 0 4 3 8 8 2 5 9]
0
[2 9]
[0 4 3 8 8 2 5 9]
[0 4]
[9 3 2]


In [11]:
# Агрегирование в одномерном массиве
print("Максимальное значение в массиве = ", a1.max())
print("Минимальное значение в массиве = ", a1.min())
print("Сумма элементов массива = ", a1.sum())

Максимальное значение в массиве =  16
Минимальное значение в массиве =  1
Сумма элементов массива =  31


In [46]:
# Создание двумерного массива (n, m)
# n - количество строк, m - количество столбцов

# С указанием значения
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

# С указанием длины и заполненного нулями
aZero = np.zeros((2, 3))
print(aZero)

# С указанием длины и заполненного единицами
aOne = np.ones((2, 3))
print(aOne)

# С указанием длины и заданным значением
aOne = np.full((2, 3), 3)
print(aOne)

# С указанием длины и заполненного случайными значениями
aRandom = np.random.random((2, 3))
print(aRandom)

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3]
 [3 3 3]]
[[0.7962878  0.585169   0.02301758]
 [0.57898035 0.09802254 0.50732864]]


In [33]:
# Арифметические операции с двумерными массивами массивом
a1 = np.random.randint(low=0, high=10, size=(2, 2))
a2 = np.random.randint(low=0, high=10, size=(2, 2))
a3 = np.random.randint(low=0, high=10, size=2)
a4 = np.random.randint(low=0, high=10, size=3)
a5 = np.random.randint(low=0, high=10, size=(2, 3))

# Сложение двух массивов одинаковой размерности
aAddition1 = a1 + a2
print("Сумма массивов ", a1, " и ", a2, " = ", aAddition1)

# Сложение двумерного массива с одномерным массивом одинаковой по ширине или длине размерности
aAddition2 = a1 + a3
print("Сумма массивов ", a1, " и ", a3, " = ", aAddition2)

# Разница двух массивов одинаковой размерности
aSubtraction1 = a1 - a2
print("Разница массивов ", a1, " и ", a2, " = ", aSubtraction1)

# Разница двумерного массива и одномерного массива одинаковой по ширине или длине размерности
aSubtraction2 = a1 - a3
print("Разница массивов ", a1, " и ", a3, " = ", aSubtraction2)

# Скалярное произведение
scalar = a1.dot(a5)
print("Скалярное произведение ", a1, " и ", a5, " = ", scalar)

Сумма массивов  [[9 3]
 [9 4]]  и  [[1 9]
 [8 5]]  =  [[10 12]
 [17  9]]
Сумма массивов  [[9 3]
 [9 4]]  и  [0 9]  =  [[ 9 12]
 [ 9 13]]
Разница массивов  [[9 3]
 [9 4]]  и  [[1 9]
 [8 5]]  =  [[ 8 -6]
 [ 1 -1]]
Разница массивов  [[9 3]
 [9 4]]  и  [0 9]  =  [[ 9 -6]
 [ 9 -5]]
Скалярное произведение  [[9 3]
 [9 4]]  и  [[1 9 0]
 [7 5 9]]  =  [[ 30  96  27]
 [ 37 101  36]]


In [34]:
# Транспонирование матрицы
a1 = np.random.randint(low=0, high=10, size=(2, 5))
print(a1)
print(a1.T)

[[1 4 6 0 6]
 [6 2 8 0 2]]
[[1 6]
 [4 2]
 [6 8]
 [0 0]
 [6 2]]


In [36]:
# Агрегирование двумерных матриц
a1 = np.random.randint(low=0, high=10, size=(2, 4))
print(a1)
print(a1.max())
print(a1.max(axis=0))
print(a1.max(axis=1))
print(a1.min())
print(a1.min(axis=0))
print(a1.min(axis=1))
print(a1.sum())
print(a1.sum(axis=0))
print(a1.sum(axis=1))

[[8 3 9 1]
 [4 5 7 9]]
9
[8 5 9 9]
[9 9]
1
[4 3 7 1]
[1 4]
46
[12  8 16 10]
[21 25]


In [41]:
# Методы матрицы
a = np.random.randint(low=0, high=10, size=(2, 5))

# Тип данных
print(a.dtype)

# Количество элементов матрицы
print(a.size)

# Размерность матрицы
print(a.ndim)

# Размеры матрицы
print(a.shape)

int32
10
2
(2, 5)
